#!/bin/sh
set -e

builddata
cleanup () {
  rm -rf "$HOME/data"
}
trap cleanup EXIT

json websites < "$HOME/data/index.json" | json -a | while read domain; do
  echo "$domain"
  checktlsconfiguration "$domain"
done
